version: '3.8'

services:
  ai-chat-app:
    image: land007/ai-chat-app:latest
    container_name: ai-chat-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # 应用配置
      - APP_NAME=${APP_NAME:-AI智能助手}
      - APP_DESCRIPTION=${APP_DESCRIPTION:-基于阿里云DashScope的智能对话}
      - WELCOME_MESSAGE=${WELCOME_MESSAGE:-}
      - CONTEXT_MESSAGE_COUNT=${CONTEXT_MESSAGE_COUNT:-5}
      # 阿里云DashScope API配置
      - DASHSCOPE_API_KEY=${DASHSCOPE_API_KEY:-your_api_key_here}
      - DASHSCOPE_API_URL=${DASHSCOPE_API_URL:-https://dashscope.aliyuncs.com/api/v1/apps/your_app_id/completion}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ai-chat-network

networks:
  ai-chat-network:
    driver: bridge
